// data-fishing.js - Complete fishing data for Stardew Valley
// Based on Stardew Valley Wiki

const FISH_DATA = [
    // ============== SPRING FISH ==============
    {
        nombre: "Anchovy",
        temporada: ["Spring", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "Any",
        dificultad: 30,
        valor: 30,
        tamaño_min: 1,
        tamaño_max: 13,
        descripcion: "A small silver fish found in the ocean."
    },
    {
        nombre: "Bream",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 PM - 2:00 AM",
        dificultad: 35,
        valor: 45,
        tamaño_min: 12,
        tamaño_max: 40,
        descripcion: "A fairly common river fish that becomes active at night."
    },
    {
        nombre: "Carp",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "Any",
        dificultad: 15,
        valor: 30,
        tamaño_min: 15,
        tamaño_max: 51,
        descripcion: "A common pond fish."
    },
    {
        nombre: "Catfish",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 75,
        valor: 200,
        tamaño_min: 28,
        tamaño_max: 94,
        descripcion: "An elusive fish found in rivers during rainy weather."
    },
    {
        nombre: "Chub",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 35,
        valor: 50,
        tamaño_min: 12,
        tamaño_max: 40,
        descripcion: "A common freshwater fish found in rivers."
    },
    {
        nombre: "Dorado",
        temporada: ["Spring", "Summer"],
        clima: "Any",
        ubicacion: "Forest River",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 78,
        valor: 100,
        tamaño_min: 20,
        tamaño_max: 50,
        descripcion: "A fierce predatory fish found in forest rivers."
    },
    {
        nombre: "Eel",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "Ocean",
        hora: "4:00 PM - 2:00 AM",
        dificultad: 70,
        valor: 85,
        tamaño_min: 30,
        tamaño_max: 100,
        descripcion: "A long, slippery fish that only comes out during rain."
    },
    {
        nombre: "Ghostfish",
        temporada: ["Spring", "Summer", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Mines (Level 20-60)",
        hora: "Any",
        dificultad: 50,
        valor: 45,
        tamaño_min: 8,
        tamaño_max: 27,
        descripcion: "A pale fish found in the underground lakes of the mines."
    },
    {
        nombre: "Herring",
        temporada: ["Spring", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "Any",
        dificultad: 25,
        valor: 30,
        tamaño_min: 10,
        tamaño_max: 35,
        descripcion: "A common ocean fish."
    },
    {
        nombre: "Largemouth Bass",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 50,
        valor: 100,
        tamaño_min: 25,
        tamaño_max: 72,
        descripcion: "A popular game fish found in mountain lakes."
    },
    {
        nombre: "Legend",
        temporada: ["Spring"],
        clima: "Rainy",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 110,
        valor: 5000,
        tamaño_min: 50,
        tamaño_max: 100,
        descripcion: "The rarest and most difficult fish to catch in Stardew Valley."
    },
    {
        nombre: "Red Mullet",
        temporada: ["Spring", "Summer"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 55,
        valor: 75,
        tamaño_min: 10,
        tamaño_max: 40,
        descripcion: "A popular ocean fish known for its red coloring."
    },
    {
        nombre: "Sardine",
        temporada: ["Spring", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 30,
        valor: 40,
        tamaño_min: 3,
        tamaño_max: 15,
        descripcion: "A common ocean fish found in large schools."
    },
    {
        nombre: "Shad",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Rainy",
        ubicacion: "River (Town + Forest)",
        hora: "9:00 AM - 2:00 AM",
        dificultad: 45,
        valor: 60,
        tamaño_min: 20,
        tamaño_max: 65,
        descripcion: "A river fish that becomes active during rain."
    },
    {
        nombre: "Smallmouth Bass",
        temporada: ["Spring", "Fall"],
        clima: "Any",
        ubicacion: "Forest River",
        hora: "Any",
        dificultad: 28,
        valor: 50,
        tamaño_min: 15,
        tamaño_max: 55,
        descripcion: "A popular game fish found in forest rivers."
    },
    {
        nombre: "Sunfish",
        temporada: ["Spring", "Summer"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 22,
        valor: 30,
        tamaño_min: 5,
        tamaño_max: 20,
        descripcion: "A common river fish with a sunny disposition."
    },
    {
        nombre: "Walleye",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "River (Town + Forest)",
        hora: "12:00 PM - 2:00 AM",
        dificultad: 45,
        valor: 105,
        tamaño_min: 20,
        tamaño_max: 60,
        descripcion: "An elusive fish that comes out during rain."
    },

    // ============== SUMMER FISH ==============
    {
        nombre: "Albacore",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 11:00 AM, 6:00 PM - 2:00 AM",
        dificultad: 60,
        valor: 75,
        tamaño_min: 20,
        tamaño_max: 45,
        descripcion: "A prized ocean fish that comes in two daily windows."
    },
    {
        nombre: "Bullhead",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "Any",
        dificultad: 46,
        valor: 75,
        tamaño_min: 15,
        tamaño_max: 50,
        descripcion: "A freshwater fish found in mountain lakes."
    },
    {
        nombre: "Halibut",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 11:00 AM, 6:00 PM - 2:00 AM",
        dificultad: 50,
        valor: 80,
        tamaño_min: 20,
        tamaño_max: 60,
        descripcion: "A flat ocean fish with both eyes on one side."
    },
    {
        nombre: "Lava Eel",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Mines (Level 100+)",
        hora: "Any",
        dificultad: 90,
        valor: 700,
        tamaño_min: 30,
        tamaño_max: 90,
        descripcion: "A rare eel that lives in the lava pools of the mines."
    },
    {
        nombre: "Octopus",
        temporada: ["Summer"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 1:00 PM",
        dificultad: 95,
        valor: 150,
        tamaño_min: 25,
        tamaño_max: 75,
        descripcion: "A clever cephalopod that's very difficult to catch."
    },
    {
        nombre: "Perch",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 35,
        valor: 55,
        tamaño_min: 10,
        tamaño_max: 40,
        descripcion: "A common freshwater fish found in rivers."
    },
    {
        nombre: "Pike",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 60,
        valor: 100,
        tamaño_min: 30,
        tamaño_max: 80,
        descripcion: "A predatory fish found in rivers."
    },
    {
        nombre: "Pufferfish",
        temporada: ["Summer"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "12:00 PM - 4:00 PM",
        dificultad: 80,
        valor: 200,
        tamaño_min: 12,
        tamaño_max: 40,
        descripcion: "A poisonous fish found in the ocean during summer."
    },
    {
        nombre: "Rainbow Trout",
        temporada: ["Summer"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 45,
        valor: 65,
        tamaño_min: 15,
        tamaño_max: 55,
        descripcion: "A colorful trout found in rivers during summer."
    },
    {
        nombre: "Red Snapper",
        temporada: ["Summer", "Fall"],
        clima: "Rainy",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 40,
        valor: 50,
        tamaño_min: 15,
        tamaño_max: 50,
        descripcion: "A popular ocean fish that comes out during rain."
    },
    {
        nombre: "Salmon",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 50,
        valor: 75,
        tamaño_min: 25,
        tamaño_max: 70,
        descripcion: "A prized fish that migrates up rivers to spawn."
    },
    {
        nombre: "Sturgeon",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 78,
        valor: 200,
        tamaño_min: 30,
        tamaño_max: 90,
        descripcion: "A large, ancient fish found in mountain lakes."
    },
    {
        nombre: "Sunfish",
        temporada: ["Spring", "Summer"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 22,
        valor: 30,
        tamaño_min: 5,
        tamaño_max: 20,
        descripcion: "A common river fish with a sunny disposition."
    },
    {
        nombre: "Super Cucumber",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 PM - 2:00 AM",
        dificultad: 80,
        valor: 250,
        tamaño_min: 18,
        tamaño_max: 60,
        descripcion: "A rare glowing sea cucumber found at night."
    },
    {
        nombre: "Tuna",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 50,
        valor: 100,
        tamaño_min: 25,
        tamaño_max: 80,
        descripcion: "A large ocean fish prized for its meat."
    },

    // ============== FALL FISH ==============
    {
        nombre: "Catfish",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 75,
        valor: 200,
        tamaño_min: 28,
        tamaño_max: 94,
        descripcion: "An elusive fish found in rivers during rainy weather."
    },
    {
        nombre: "Eel",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "Ocean",
        hora: "4:00 PM - 2:00 AM",
        dificultad: 70,
        valor: 85,
        tamaño_min: 30,
        tamaño_max: 100,
        descripcion: "A long, slippery fish that only comes out during rain."
    },
    {
        nombre: "Midnight Carp",
        temporada: ["Fall", "Winter"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "10:00 PM - 2:00 AM",
        dificultad: 55,
        valor: 150,
        tamaño_min: 15,
        tamaño_max: 45,
        descripcion: "A nocturnal fish found in mountain lakes at night."
    },
    {
        nombre: "Salmon",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 50,
        valor: 75,
        tamaño_min: 25,
        tamaño_max: 70,
        descripcion: "A prized fish that migrates up rivers to spawn."
    },
    {
        nombre: "Tiger Trout",
        temporada: ["Fall", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 60,
        valor: 150,
        tamaño_min: 15,
        tamaño_max: 50,
        descripcion: "A rare hybrid trout with striking tiger stripes."
    },
    {
        nombre: "Walleye",
        temporada: ["Spring", "Fall"],
        clima: "Rainy",
        ubicacion: "River (Town + Forest)",
        hora: "12:00 PM - 2:00 AM",
        dificultad: 45,
        valor: 105,
        tamaño_min: 20,
        tamaño_max: 60,
        descripcion: "An elusive fish that comes out during rain."
    },

    // ============== WINTER FISH ==============
    {
        nombre: "Albacore",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 11:00 AM, 6:00 PM - 2:00 AM",
        dificultad: 60,
        valor: 75,
        tamaño_min: 20,
        tamaño_max: 45,
        descripcion: "A prized ocean fish that comes in two daily windows."
    },
    {
        nombre: "Halibut",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 11:00 AM, 6:00 PM - 2:00 AM",
        dificultad: 50,
        valor: 80,
        tamaño_min: 20,
        tamaño_max: 60,
        descripcion: "A flat ocean fish with both eyes on one side."
    },
    {
        nombre: "Ice Pip",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "Mines (Level 60+)",
        hora: "Any",
        dificultad: 85,
        valor: 500,
        tamaño_min: 15,
        tamaño_max: 45,
        descripcion: "A rare fish found in the frozen levels of the mines."
    },
    {
        nombre: "Lingcod",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 50,
        valor: 120,
        tamaño_min: 30,
        tamaño_max: 70,
        descripcion: "A winter fish known for its aggressive behavior."
    },
    {
        nombre: "Midnight Carp",
        temporada: ["Fall", "Winter"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "10:00 PM - 2:00 AM",
        dificultad: 55,
        valor: 150,
        tamaño_min: 15,
        tamaño_max: 45,
        descripcion: "A nocturnal fish found in mountain lakes at night."
    },
    {
        nombre: "Perch",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 35,
        valor: 55,
        tamaño_min: 10,
        tamaño_max: 40,
        descripcion: "A common freshwater fish found in rivers."
    },
    {
        nombre: "Pike",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "Any",
        dificultad: 60,
        valor: 100,
        tamaño_min: 30,
        tamaño_max: 80,
        descripcion: "A predatory fish found in rivers."
    },
    {
        nombre: "Sardine",
        temporada: ["Spring", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 30,
        valor: 40,
        tamaño_min: 3,
        tamaño_max: 15,
        descripcion: "A common ocean fish found in large schools."
    },
    {
        nombre: "Sturgeon",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 78,
        valor: 200,
        tamaño_min: 30,
        tamaño_max: 90,
        descripcion: "A large, ancient fish found in mountain lakes."
    },
    {
        nombre: "Tiger Trout",
        temporada: ["Fall", "Winter"],
        clima: "Any",
        ubicacion: "River (Town + Forest)",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 60,
        valor: 150,
        tamaño_min: 15,
        tamaño_max: 50,
        descripcion: "A rare hybrid trout with striking tiger stripes."
    },
    {
        nombre: "Tuna",
        temporada: ["Summer", "Winter"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 50,
        valor: 100,
        tamaño_min: 25,
        tamaño_max: 80,
        descripcion: "A large ocean fish prized for its meat."
    },
    {
        nombre: "Void Salmon",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "Witch's Swamp",
        hora: "Any",
        dificultad: 80,
        valor: 150,
        tamaño_min: 15,
        tamaño_max: 45,
        descripcion: "A dark fish found in the Witch's Swamp."
    },

    // ============== SPECIAL / LEGENDARY FISH ==============
    {
        nombre: "Angler",
        temporada: ["Fall"],
        clima: "Any",
        ubicacion: "River (North of Pelican Town)",
        hora: "Any",
        dificultad: 85,
        valor: 900,
        tamaño_min: 20,
        tamaño_max: 60,
        descripcion: "A legendary fish known for its glowing lure."
    },
    {
        nombre: "Crimsonfish",
        temporada: ["Summer"],
        clima: "Any",
        ubicacion: "Ocean (East Beach)",
        hora: "Any",
        dificultad: 95,
        valor: 1500,
        tamaño_min: 30,
        tamaño_max: 70,
        descripcion: "A legendary fish with striking red coloring."
    },
    {
        nombre: "Glacierfish",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "River (South of Cindersap Forest)",
        hora: "Any",
        dificultad: 100,
        valor: 1000,
        tamaño_min: 25,
        tamaño_max: 65,
        descripcion: "A legendary fish found in frozen waters."
    },
    {
        nombre: "Legend",
        temporada: ["Spring"],
        clima: "Rainy",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 110,
        valor: 5000,
        tamaño_min: 50,
        tamaño_max: 100,
        descripcion: "The rarest and most difficult fish to catch in Stardew Valley."
    },
    {
        nombre: "Mutant Carp",
        temporada: ["Spring", "Summer", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Sewers",
        hora: "Any",
        dificultad: 80,
        valor: 1000,
        tamaño_min: 35,
        tamaño_max: 80,
        descripcion: "A mutant fish found in the sewers."
    },
    {
        nombre: "Son of Crimsonfish",
        temporada: ["Summer"],
        clima: "Any",
        ubicacion: "Ocean (East Beach)",
        hora: "Any",
        dificultad: 95,
        valor: 1500,
        tamaño_min: 25,
        tamaño_max: 60,
        descripcion: "The offspring of the legendary Crimsonfish."
    },
    {
        nombre: "Ms. Angler",
        temporada: ["Fall"],
        clima: "Any",
        ubicacion: "River (North of Pelican Town)",
        hora: "Any",
        dificultad: 85,
        valor: 900,
        tamaño_min: 18,
        tamaño_max: 55,
        descripcion: "The offspring of the legendary Angler."
    },
    {
        nombre: "Legend II",
        temporada: ["Spring"],
        clima: "Rainy",
        ubicacion: "Mountain Lake",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 110,
        valor: 5000,
        tamaño_min: 45,
        tamaño_max: 95,
        descripcion: "The offspring of the legendary Legend fish."
    },
    {
        nombre: "Radioactive Carp",
        temporada: ["Spring", "Summer", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Sewers",
        hora: "Any",
        dificultad: 80,
        valor: 1000,
        tamaño_min: 30,
        tamaño_max: 75,
        descripcion: "A mutated carp found in the sewers."
    },
    {
        nombre: "Glacierfish Jr.",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "River (South of Cindersap Forest)",
        hora: "Any",
        dificultad: 100,
        valor: 1000,
        tamaño_min: 20,
        tamaño_max: 58,
        descripcion: "The offspring of the legendary Glacierfish."
    },

    // ============== NIGHT MARKET / WINTER SPECIAL ==============
    {
        nombre: "Blobfish",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "Night Market Submarine",
        hora: "Any",
        dificultad: 75,
        valor: 500,
        tamaño_min: 10,
        tamaño_max: 35,
        descripcion: "A strange fish found in the Night Market submarine."
    },
    {
        nombre: "Midnight Squid",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "Night Market Submarine",
        hora: "Any",
        dificultad: 55,
        valor: 100,
        tamaño_min: 10,
        tamaño_max: 30,
        descripcion: "A squid found in the Night Market submarine."
    },
    {
        nombre: "Spook Fish",
        temporada: ["Winter"],
        clima: "Any",
        ubicacion: "Night Market Submarine",
        hora: "Any",
        dificultad: 60,
        valor: 220,
        tamaño_min: 10,
        tamaño_max: 35,
        descripcion: "A ghostly fish found in the Night Market submarine."
    },

    // ============== OTHER LOCATIONS ==============
    {
        nombre: "Flounder",
        temporada: ["Spring", "Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "6:00 AM - 7:00 PM",
        dificultad: 35,
        valor: 100,
        tamaño_min: 10,
        tamaño_max: 30,
        descripcion: "A flat ocean fish that feeds on the sea floor."
    },
    {
        nombre: "Lionfish",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "Any",
        dificultad: 50,
        valor: 100,
        tamaño_min: 10,
        tamaño_max: 30,
        descripcion: "A venomous fish with striking striped fins."
    },
    {
        nombre: "Stingray",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "Any",
        dificultad: 60,
        valor: 180,
        tamaño_min: 20,
        tamaño_max: 50,
        descripcion: "A flat ocean fish with a venomous barb."
    },
    {
        nombre: "Blue Discus",
        temporada: ["Summer", "Fall"],
        clima: "Any",
        ubicacion: "Ocean",
        hora: "Any",
        dificultad: 40,
        valor: 120,
        tamaño_min: 10,
        tamaño_max: 30,
        descripcion: "A brightly colored fish with a round body."
    },
    {
        nombre: "Slimejack",
        temporada: ["Spring", "Summer", "Fall", "Winter"],
        clima: "Any",
        ubicacion: "Mutant Bug Lair",
        hora: "Any",
        dificultad: 45,
        valor: 100,
        tamaño_min: 15,
        tamaño_max: 40,
        descripcion: "A slimy fish found in the Mutant Bug Lair."
    }
];